### PR TITLE
better error handling

### LINKED ISSUE #20: Exceptions thrown in callback are being caught and ignored
``` javascript
  publish(foo, bar, function(err) {
    undefined();
  });
```
will fail silently, making it hard to find errors.

### PR DESCRIPTION
**Pull request by timaschew**
- provide error handling for callback
- provide default error handling if no callback is passed

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -48,14 +48,27 @@ function getRepo(options) {
...
-    done = config;
+    callback = config;
     config = {};
   }
 
+  var done = function(arguments) {
+    try {
+      (callback || function(err) {
+        if (!err) {
+          console.log(err)
```
Comment (tschaub) [inline lib/index.js]: Do you really mean to only log here if `!err`?

Comment (timaschew) [inline lib/index.js]: Yes.
I think if the caller is not interested in handling any successful callback, because it's the last action anyway or so, then he should be notified in the error case.

But you can also omit the logging in the binary here https://github.com/tschaub/gh-pages/blob/master/bin/gh-pages#L35
and do a successful log in this file.

Comment (tschaub) [inline lib/index.js]: I'm just confused why you would want to log `undefined` or other falsy values.

To be clear, did you mean to write this:
```js
if (err) {
  console.log(err);
}
```
instead of this:
```js
if (!err) {
  console.log(err);
}
```
?

Comment (timaschew) [inline lib/index.js]: Sorry, you're right, I edit my previous answer.
But `if (err){}` didn't work, the error is falsy, so `!!err` handles it the right way or `err != null`

Comment (timaschew) [inline lib/index.js]: and `err != null` was linted with this error: `gh-pages/lib/index.js
  63:13  error  Use ‘===’ to compare with ‘null’  no-eq-null`

which is really sad, because null check with `!=` makes sense to check against `undefined` and `null`

Comment (timaschew) [inline lib/index.js]: haha `!!` is not allowed too.

So either one of the rules needs to be disabled or the check should be 
`if (typeof err !== 'undefined' && err !== null) {}`

Comment (tschaub) [inline lib/index.js]: @timaschew you can just write this:
```js
if (err) {
  // do something
}
```

This behaves exactly the same as this:
```js
if (!!err) {
  // do something
}
```

Comment (timaschew) [inline lib/index.js]: That's true ^^ 
I tried this in the morning today, but seems that I was confused a little bit...
