### PR TITLE
Fix remove not working properly

### LINKED ISSUE #334: bug: README options 'remove' is not functioning as described
I have reviewed the source code and find out that in CLI mode, remove is treated as only. Howerver, in programing mode which I "require('gh-pages')" the following code wont work as source code "config.remove" has never been used.

```javascript
ghpages.publish('dist', {
  remove: "*.json"
}, callback);
```

### LINKED ISSUE #337: empty string is not a valid pathspec
When I try to run 
```
gh-pages -d build -e myproject -v myproject
```
Im getting this error, why?
```
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
```

_Im using gh-pages version 2.2.0_

### PR DESCRIPTION
**Pull request by sunghwan2789**
This PR fixes some issues described below and resolves #334, fixes #337 .

## Remove globbed files

https://github.com/tschaub/gh-pages/blob/3579ab235d5502a2a1dc4d2f18ec1c9dce03f94a/lib/index.js#L156

Joining files in a string causes incorrect shell argument passing. A globbed file can be removed, but globbed files cannot be removed since the actual command will be

```
git rm -r -f "abc.js abc.css"
```

This PR makes `git.rm` and `git.add` accept `string[]` and handle them properly.

## Remove files in remote dist directory, not in local one

https://github.com/tschaub/gh-pages/blob/3579ab235d5502a2a1dc4d2f18ec1c9dce03f94a/lib/index.js#L97-L99

This shows that **gh-pages** globs files to be removed in local dist directory, not in remote branch. It causes git a fatal error(like #337) since it tries to remove files that are not in remote dist directory. `globby.sync` should be executed in remote dist directory.

## Skip removing files if there are no globbed files

When [`globby.sync`](https://github.com/tschaub/gh-pages/blob/3579ab235d5502a2a1dc4d2f18ec1c9dce03f94a/lib/index.js#L97-L99) globs files, it returns empty array if there are no files to be removed. A guard of it should be added before 

https://github.com/tschaub/gh-pages/blob/3579ab235d5502a2a1dc4d2f18ec1c9dce03f94a/lib/index.js#L156

### CODE REVIEW

**Comment by codler** [comment]
I encountered this bug also, i hope this will be merged

**Comment by tschaub** [comment]
Thanks for the proposed fix, @sunghwan2789.

Can you please remove the added `.prettierrc` file?  Formatting is handled by ESLint, and editor integrations should be able to use the `eslintConfig` member already in the `package.json`.

**Comment by sunghwan2789** [comment]
Oh I did not notice that. Removed now!

File: lib/index.js [hunk 1]
```diff
@@ -31,7 +31,7 @@ exports.defaults = {
   branch: 'gh-pages',
   remote: 'origin',
   src: '**/*',
-  only: '.',
+  remove: '.',
```
Comment (tschaub) [inline lib/index.js]: This default scares me.  I haven't found time to do a more thorough review, but I don't get why we would want to remove everything by default.

Comment (tschaub) [reply lib/index.js]: Scratch that, I see that is the currently documented behavior.  Clearly I need to get my head back into this before understanding if this change does the right thing.

Comment (sunghwan2789) [reply lib/index.js]: I think removing all files default seems ok to me, as `options.add` is present for controlling this behaviour.
For a reference, please take a look  https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-keeping-existing-files

**Comment by tschaub** [comment]
Thanks for your work on this, @sunghwan2789.
